wdn/templates_4.0/scripts/search.js

Local sites should only be allowed to append the U or CX querystring
params for use in the WDN search tool.
Logic has been added to enforce the use of ONLY the UNL Search app from
the WDN search tool.
This commit also removes the experimental speak-to-text attribute that
has been removed from the only browser that supported it.
The undocumented feature to add a local placeholder has also been
removed (unapproved by the style guide)

Fix the algorithm of allowing UNL Search URL extending

---

wdn/templates_4.0/scripts/navigation.js

When scrolling down a long page of information on a touch enabled mobile device, it was easy to accidentally open the side navigation.  This was frustrating and not expected.  This commit aims to address that issue by doubling the distance required to swipe for the navigation to open.  While it might not be a perfect solution, it is hopefully better than it used to be.
Maybe it would be better to remove this feature altogether?

increase swipe length required to open navigation

---

wdn/templates_4.0/scripts/events.js

The link was not going to the correct feed. This two character change makes it have the right format.

Fix events RSS link on upcoming list.

---

sharedcode/affiliate/css/affiliate.css
sharedcode/affiliate/less/affiliate.less

The defined media query was the opposite of the intended style. The affilate background color should be changed for narrower browser widths, not wider. I also added white as the color to replace the very light pink used in the WDN Framework.

Updated media query for Affiliate CSS

---

wdn/templates_4.0/scripts/main.js

This script was outputting too much data for too little ROI (users are, in fact, scrolling) so it should be turned off.

Remove analytics scroll depth plugin

---

wdn/templates_4.0/less/modules/forms.less

Normal buttons don't have it and it causes the buttons to appear
slightly bigger than their enabled counterparts.

Remove box-shadow from disabled buttons

---

Makefile
wdn/templates_4.0/less/layouts/extlatin.less
wdn/templates_4.0/less/layouts/smallcaps.less
wdn/templates_4.0/scripts/extlatin.js
wdn/templates_4.0/scripts/smallcaps.js

Extended font features can optionally be included via JavaScript.

Extend font features (small caps, extended Latin)

---

debug.shtml
wdn/templates_4.0/examples/notice.html
wdn/templates_4.0/less/layouts/bands.less
wdn/templates_4.0/less/modules/notices.less
wdn/templates_4.0/scripts/band_imagery.js
wdn/templates_4.0/scripts/carousel.js
wdn/templates_4.0/scripts/events-band.js
wdn/templates_4.0/scripts/events.js
wdn/templates_4.0/scripts/extlatin.js
wdn/templates_4.0/scripts/form_validation.js
wdn/templates_4.0/scripts/jqueryui.js
wdn/templates_4.0/scripts/mediaelement_wdn.js
wdn/templates_4.0/scripts/modal.js
wdn/templates_4.0/scripts/modernizr-wdn.js
wdn/templates_4.0/scripts/monthwidget.js
wdn/templates_4.0/scripts/notice.js
wdn/templates_4.0/scripts/rss_widget.js
wdn/templates_4.0/scripts/smallcaps.js
wdn/templates_4.0/scripts/tooltip.js
wdn/templates_4.0/scripts/unlalert.js
wdn/templates_4.0/scripts/wdn.js

* Reverts bad commit to debug html instance
* Changes the example markup for notice
* Updates the core band styles to use margin to offset the page-pad on mobile
* Updates notice styles to not do so many overrides
* Cleanup WDN api to remove dead code and add a method for getting a versioned template file URL
* Update all modules to use the versioned template file URL getter for loading CSS.

Update Notice Module and Module CSS loading API

---

wdn/templates_4.0/scripts/idm.js

If these fields are available the first letter of the surname will no
longer be added. Otherwise, the full "display name" will be used.
Closes #751.

Use only nickname or first name in IdM module

---

wdn/templates_4.0/scripts/legacy.js

* The campus service has moved and now works on https
* XP can present itself at Windows NT 5.2 (from browserstack tests)

Fix the Windows XP notice display

---

wdn/templates_4.0/scripts/main.js
wdn/templates_4.0/scripts/skipnav.js

This fixes an issue where if the skipnav link was clicked, focus was not being set to the #maincontent div.  The screen would just visually focus on the area, rather than move tab focus to the maincontent area.
fixes #829

Give #maincontent focus on skipnav click

---

wdn/templates_4.0/scripts/search.js

This does two things to improve a11y for the search feature.
1. fixes #885 - Pressing escape will close the results pane.  This could be further improved by adding a link to close the results pane (but I'm not sure exactly how the would look).
2. Send focus to the results pane on manual submit (not autocomplete)
Note that an update to the search application will have to be rolled out at the same time.  There is a paired PR for that project which I will submit in just a second.

Improve a11y for the search feature

---

wdn/templates_4.0/scripts/search.js

In firefox, the form was being submitted before being closed, and thus re-opened right away, appearing as a flash.

Fix bug in firefox where search was not being closed

---

wdn/templates_4.0/scripts/search.js

Setting the input value to '' causes FireFox to mark the input as invalid because it is required.  To prevent this, simply reset the form instead.

Prevent validation styles from showing on search close

---

wdn/templates_4.1/less/states/search.less

Using display:block and display:none removes the existing transitions for the dropdowns.

Revert to previous dropdown styles

---

wdn/templates_4.1/scripts/wdn-ui.js

This was causing JS to fail in some browsers
This should be released ASAP as it is actively breaking pages.

Add a missing bracket

---

sharedcode/affiliate/localFooter.html
sharedcode/localFooter.html
wdn/templates_4.1/includes/globalfooter.html
wdn/templates_4.1/less/layouts/footer.less

Don't rely on the `wdn-footer-heading` cass, which would still work if the `role="heading"` attribute was missing. By writing the css to require the `role="heading"`, people will be less likely to forget that attribute.
I found this while updating some applications to use 4.1. I hope it isn't too late to make this change.

Enforce a11y for headings in footer

---

wdn/templates_4.1/includes/globalfooter.html
wdn/templates_4.1/less/_mixins/colors.less
wdn/templates_4.1/less/layouts/breadcrumbs.less
wdn/templates_4.1/less/layouts/navigation.less
wdn/templates_4.1/less/layouts/search.less
wdn/templates_4.1/less/layouts/share.less
wdn/templates_4.1/less/states/navigation.less

Update UNL scarlet to #dd0000
Adjust layout of last-link breadcrumb
Adjust border-color for mobile navigation links
Position share widget on right edge of content instead of moving with navigations that have fewer than six primary links
Add border-bottom for primary navigation links without children

Breadcrumb, navigation, color updates

---

wdn/templates_4.1/less/_mixins/colors.less

We've decided not to go with #dd0000 after all.

Revert scarlet to #d00000

---

wdn/templates_4.1/less/states/share.less

Share widget didn't move when user is scrolling and opens mobile nav tray. (It overlapped the breadcrumbs in the tray.) Removing position:fixed (which isn't needed anyway) fixes this behavior.

Share widget/mobile nav scrolling

---

wdn/templates_4.1/less/modules/bands.less

Add support for band with scarlet background. This includes a subtle top-to-bottom linear gradient to help differentiate a scarlet band from the scarlet sticky navigation bar.

Scarlet band

---

wdn/templates_4.1/less/layouts/breadcrumbs.less

This reduces the height of the breadcrumbs and better vertically centers the last-child breadcrumb with the others. 
I'd like to continue to improve and iterate on the breadcrumbs, but I think this wraps up work on breadcrumbs for the initial release of 4.1.
Closes #905

Reduce breadcrumb height

---

.gitignore
.travis.yml
tests/Accessibility/accessibility.phpt
tests/config.sample.php
wdn/templates_4.1/less/layouts/footer.less

This should fix a11y tests that have been broken for 4.1.  (its a good thing I double checked them).
This also makes it easier to test without vagrant and improves the output of tests.

Fix a11y tests

---

wdn/templates_4.1/less/modules/promo-image.less

The default display of a CSS gradient is from top to bottom, therefore, the 'top' is not needed. When the vendor prefixes were removed, 'top' should have been removed, too.

Adjust promo image background gradient

---

wdn/templates_4.1/includes/idm.html
wdn/templates_4.1/includes/search.html
wdn/templates_4.1/scripts/idm.js

When logged out, an empty `label` was available to the a11y api. Use best practices for buttons with no visible text for the search feature.

A11y improvements

---

wdn/templates_4.1/scripts/navigation.js

The bug fix from b042326f856964ea9f6c6058b29ef9b0e88e860c
resolved the exception that was occurring in switchNavigation on
navigation collapse. However, it revealved that the variable reference
was not correct (after wrapInner does its magic). This caused an issue
where the active breadcurb (home navigation) could not be determined and
was removed when the navigation proxy returned a new home navigation
list.
A workaround for this issue would be to always have your home breadcrumb
be a link (as is required by the style guide).

Fix home pages without home breadcrumb link lose nav on collapse

---

wdn/templates_4.1/scripts/idm.js

It looks like there was a race condition. Website can set the login URL with JS, which will also cause `displayLogin()` to be called. `displayLogin()` would remove the `.loggedin` class from IDM container (but not remove the profile image, etc).  This would cause weird styling.
If a user is already logged in, the `displayLogin()` method should never be called, so prevent it from doing anything.

Fix login link race condition

---

wdn/templates_4.1/less/layouts/bands.less

The text-band should be centered with a max-width of 50rem, but using margin: 0 auto; to center the content removes the left and right margins, resulting in text that runs right up to the viewport edge. This commit keeps the margins at narrower browser widths (where the length of the text never exceeds 50rem), and instead removes them and applies the 50rem max-width at 960px, where the viewport exceeds the width of the content and margins combined.

Text band margins

---

wdn/templates_4.1/scripts/search.js

Slow typing is causing too many queries on the search apps. This new
setup will immediately load/display the search iframe (with a loading
indicator) and only issue a submit after a full second of inactivity on
the keyboard.

Improve iframe (desktop) search auto-submit timing

---

wdn/templates_4.1/scripts/modernizr-wdn.js

* The Video Autoplay test will help developers provide fallback content (usually in the form of poster images) for browsers (usually mobile) that don't support automatic playback of video content.
* The Object Fit test will allow developers to take advantage of the [object-fit property](https://dev.opera.com/articles/css3-object-fit-object-position/) for greater control over how images scale and fit inside parent element containers, and provide fallback layouts for the Microsoft browsers that don't support this useful property.

Add Modernizr tests for Video Autoplay, Object Fit

---

wdn/templates_4.1/less/layouts/share.less
wdn/templates_4.1/less/states/share.less

FYI: I thought I had undid commit 1a61334, but it is included (and changed by a subsequent commit) here. I don't think its inclusion necessarily hurts anything.
I will continue to work on visual improvements related to this update before (and possibly after, too) deployment next week.

Fixed position share menu on scroll

---

Gruntfile.js
wdn/templates_4.1/includes/scriptsandstyles.html
wdn/templates_4.1/includes/scriptsandstyles_debug.html
wdn/templates_4.1/includes/scriptsandstyles_local.html
wdn/templates_4.1/less/all.less
wdn/templates_4.1/less/print.less

Removes 2 network requests for css related items (print sheet and large SVG image).

Remove some more network requests

---

wdn/templates_4.1/examples/hero.html
wdn/templates_4.1/less/modules/hero.less

**Temporary Modernizr videoautoplay fallback**
As it turns out, the videoautoplay Modernizr test is [is not entirely reliable](Modernizr/Modernizr#1095). @mfairchild365 has submitted [a pull request](Modernizr/Modernizr#1963) to Modernizr which has been merged. In the meantime, I've adjusted the hero content CSS. The video will always play if the videoautoplay test works. If the test fails, we'll fall back to media queries. Video will be shown for browser widths greater than 768px.
**Markup and CSS updates to fix the broken navigation bug in Edge**
Markup and CSS updates to fix the broken navigation bug in Edge. By wrapping the image and video elements in parent containers and placing the overflow:hidden and opacity on the parents, the Edge bug is avoided. Fixes #983

Hero content updates

---

wdn/templates_4.1/less/base/helpers.less

This will remove the need for inline styles on the iframe or use of the now invalid `frameborder` attribute

Remove the border from responsive embeds by default

---

wdn/templates_4.1/less/modules/hero.less

* A media query still referenced .wdn-hero-poster, updated to .wdn-hero-picture
* Set wdn-hero-picture image width to 100%
* Set wdn-hero-picture image to display as a block, removing unwanted space below image, visible between 768–960px

Hero layout fixes

---

wdn/templates_4.1/less/base/text.less
wdn/templates_4.1/less/layouts/forms.less
wdn/templates_4.1/less/layouts/navigation.less
wdn/templates_4.1/less/layouts/noscript.less
wdn/templates_4.1/scripts/js-css/display-font.less

- Remove ligatures from core webfonts (used only by Mercury Display)
- Update kerning and ligature CSS for Mercury Display
- Remove 'font-kerning' declaration
- Remove redundant kerning declarations
- Remove sans serif font weight bold

Font styling updates

---

wdn/templates_4.1/less/layouts/header.less

This will ensure that main content elements that are absolutely- or fixed-positioned won't appear behind the header if positioned at the top of the page.
As an example, Richard is using psuedo content to attach a fixed-position element with a background-image to his site for better scrolling performance and display consistency on mobile vs desktop: http://unlcms.unl.edu/businessandfinance/parking-2/welcome

Add bg-color to header

---

wdn/templates_4.1/less/modules/hero.less

* Changed video to display: block (Same issue as #04575910)
* Added object-fit support for hero videos and images
FYI, I'll likely have more updates on the way.

More wdn-hero updates

---

wdn/templates_4.1/scripts/wdn-ui.js

The aria-hidden attribute was not being toggled correctly. Once it was set to `aria-hidden="false"` it would not be toggled back to `aria-hidden="true"`.

Toggle the container's aria-hidden attribute

---

wdn/templates_4.1/less/modules/images.less

Based on some recent suggestions:
- "suggest changing font color to match the body text color, the default color dark brown color #655114 doesn't go with any other default colors on the site"—Removed figcaption specific color, will inherit WDN HMTL color (#5b5b5a) instead
- "suggest changing font to a san-serif to make it easier to read since it's so tiny"—Changed figcaption to sans-serif font to further set it apart from serif body copy and bring it closer inline with the captions used on the recently-redesigned UNL Today.

Figcaption styling updates

---

wdn/templates_4.1/examples/events.html

HTTPS is getting to be required for Safari and IE sometimes, so let's stick that in the example to show users what to do.

Update example to encourage https

---

wdn/templates_4.1/includes/globalfooter.html

Justin Chase Brown, Director of Scholarships & Financial Aid, emailed us to let us know that "[d]ue to HLC accreditation and federal regulations, our ‘student information disclosures’ must be positioned more prominently on the main UNL website." He asked that the title of the link be “Student Information Disclosures” and link to [http://heoa.unl.edu/](http://heoa.unl.edu/).

Add Student Information Disclosures link to footer

---

wdn/templates_4.1/less/modules/promo-image.less

I received feedback that the promo image layout has some issues: “Promo image text doesn't display well on mobile. It's too large and has too much line-height. It often overlaps the red nav bar on mobile. Can you make the text and line height smaller at the 480px breakpoint by default?”
This update:
* Reduces font-size for browser widths < 768px wide
* Removes pixel-based font-size fallbacks
* Specifies a line-height of 1
* Adds a left and right margin so text does not run to the edge of the browser chrome
* Adds margin-top to anchors (buttons) that immediately follow the promo text to provide adequate vertical space in between

Improve promo-image layout

---

wdn/templates_4.1/less/states/regions.less

Corrected layout issues for [regions that may be conditionally hidden](http://wdn.unl.edu/unledu-41-style-book#exceptions)

Improve layout of hidden regions

---

.gitignore
debug.shtml
scripts/generateHiddenRegionTests.php

This is a convenience script which generates pages that would help with manual testing of the hide-classes.
Just from reviewing these, it looks like some of the footer related ones still don't work. =/

Add a script to generate pages to help test hide-classes

---

wdn/templates_4.1/scripts/analytics.js

See https://github.com/unl/UNL_MediaHub/issues/319 and depends on https://github.com/unl/UNL_MediaHub/pull/322
To implement, a developer would have to do the following on every page which they want to record these events:
```
<script>
require(['analytics'], function(analytics) {
analytics.recordMediaHubEvents();
});
</script>
```

Add a method to record mediahub iframe events to ga

---

wdn/templates_4.1/less/modules/hero.less

At shorter heights, the picture or video would shrink and reveal the background-color of the hero container. This ensures that imagery always covers the hero container.

Add min-height to WDN hero video and picture

---

wdn/templates_4.1/includes/globalfooter.html

The ‘About the Big Ten Conference’ page has been renamed ‘Academic Partnerships.’ The content wasn’t exclusively about the Big Ten Conference, but also included content about the Big Ten Academic Alliance and Association of Public and Land-Grant Universities (APLU). The URL has been updated to reflect the new name. Likewise, I’m updating the link in the global footer.

Update Big Ten logo link to Academic Partnerships

---

wdn/templates_4.1/less/layouts/breadcrumbs.less
wdn/templates_4.1/less/layouts/content_wrapper.less
wdn/templates_4.1/less/layouts/footer.less
wdn/templates_4.1/less/layouts/forms.less
wdn/templates_4.1/less/layouts/grid.less
wdn/templates_4.1/less/layouts/header.less
wdn/templates_4.1/less/layouts/idm.less
wdn/templates_4.1/less/layouts/navigation.less
wdn/templates_4.1/less/layouts/resources.less
wdn/templates_4.1/less/layouts/search.less
wdn/templates_4.1/less/modules/promo-image.less
wdn/templates_4.1/scripts/js-css/band_imagery.less
wdn/templates_4.1/scripts/js-css/display-font.less
wdn/templates_4.1/scripts/js-css/events-band.less
wdn/templates_4.1/scripts/js-css/events.less
wdn/templates_4.1/scripts/js-css/extlatin.less
wdn/templates_4.1/scripts/js-css/formvalidator.less
wdn/templates_4.1/scripts/js-css/monthwidget.less
wdn/templates_4.1/scripts/js-css/notices.less
wdn/templates_4.1/scripts/js-css/rsswidget.less
wdn/templates_4.1/scripts/js-css/smallcaps.less
wdn/templates_4.1/scripts/js-css/unlalert.less

Update framework CSS to conform to [IIM code standards](https://github.com/unl/iim-code-standards/blob/gh-pages/index.html)

Code cleanup

---

wdn/templates_4.1/less/modules/images.less

aXe reports the opacity of the figcaption in the [animated caption](http://wdn.unl.edu/images) as an error. While adjusting the opacity could resolve it, this error shines a light on other problems with this design pattern. The caption is hidden by default and shown only on hover, leaving no way to access the content on devices that don't support hover events (i.e. touch screens). Unless there is a focusable item in the figcaption, this content will also not be keyboard accessible. We should strive to show content by default and hide it only when there's a demonstrated need. That need should then be addressed with an interface that makes the reason for—and interactions with—hidden content clear to the user.
Despite working ok for me, @mfairchild365 has found that the caption does not …

Remove animated caption

---

wdn/templates_4.1/less/modules/hero.less

Despite clearing my history, I continue to see unwanted artifacts in the hero text-shadow in Chrome—both while logged in _and_ out of UNLcms. Even if it is just me, the smaller text-shadow will provide a bit more contrast around letters instead of being more diffused.
.

Decrease hero text-shadow

---

wdn/templates_4.1/less/layouts/bands.less

Add margin-bottom to last-child element (if not a .wdn-band) of #maincontent to add vertical space between main content and footer.
If someone can think of a better way of doing this, I'm all ears.

Add vertical space between main content and footer

---

wdn/templates_4.1/scripts/carousel.js

The direction nav fails accessibility audits by default because in its 'hidden' state, the navigation is still in the DOM and focusable. However, when focused with a keyboard, they are not shown, and thus can cause confusion (where is the current focus?). Additionally, the animation to show them on hover floats them in from the sides and can create a confusing and moving click target. Let's just disable them for now.

 carousel: Disable The direction nav by default

---

wdn/templates_4.1/scripts/events-band.js
wdn/templates_4.1/scripts/events.js
wdn/templates_4.1/scripts/monthwidget.js

Safari, mobile Safari, and occasionally IE/Edge (some versions)
would not correctly upgrade requests to the UNL Events API
to https. This would cause a CSRF warning and the request would
fail, causing the events widget not to appear. The problem was
fixed by the user entering https:// before their calendar URL
as opposed to just //, but this patch forces https:// if the
user had the old way put in.
Fixes card
https://trello.com/c/7c3VGIvp/60-events-widget-force-https-urls-for-parameters-in-the-widget

Force events widgets to use https to retrieve events

---

wdn/templates_4.1/less/layouts/tables.less
wdn/templates_4.1/less/modules/tables.less

Some table colors did not meet color contrast compliance. The colors, background-colors, and border colors have been adjusted.
Table zebra-striping has been improved for @bp-under768w by applying alternating stripes directly to the stacking <td> cells… 
…instead of to the table rows.
Border-collapse has been set to separate for responsive tables. Dark borders were overlapping lighter borders:
This pull request also includes some general code cleanup.
Fixes #1056.

Table color improvements

---

wdn/templates_4.1/scripts/js-css/events-band.less

Outline was set to zero for events-band links (cards) with no alternative styles provided for when they are in focus. [Resource](http://www.outlinenone.com/)
-Added focus styles to event band links including view more events link at the bottom of the band.
-Added two color variables in events-band.less: @events-darkblue, and @events-darkbluegray
Changes to be committed:
modified:   wdn/templates_4.1/scripts/js-css/events-band.less

Fix: Adding focus for events-band

---

wdn/templates_4.1/less/layouts/breadcrumbs.less

After updating Chrome, an unwanted space adjacent to the breadcrumb arrow has appeared at various widths.
My hunch is that this is caused by Chrome's [recently added support for subpixel layout of borders](https://chromium.googlesource.com/chromium/src/+/934becac5daa91ea979fb66e4ae21761ca11ebc9). 
By replacing `right: 0;` and `transform: translateX(100%);` with `left: 100%;`, the unwanted space goes away. So does an extra line (or two, counting vendor prefixes) of code!

Breadcrumb arrow layout fix

---

wdn/templates_4.1/less/layouts/forms.less

`cursor: pointer` was removed in a recent update to normalize.css. This commit restores the style for buttons and related form elements.

Restore button cursor lost in normalize.css update

---

wdn/templates_4.1/less/layouts/forms.less

Tested in Chrome, FF, Safari
Before:
After:

Fix the visual height of the button within .wdn-input-group-btn

---

debug.shtml
wdn/templates_4.1/less/layouts/tables.less
wdn/templates_4.1/less/modules/tables.less

- Fixed `th` of `thead` in .wdn_responsive_table.flush-left to text align left instead of centered due to specificity overrides
- Changed color and background color of `th` in `tbody` to resolve contrast issues for all the different table color variations.

Fixes: Text alignment and color contrast fix for framework table styles 

---

wdn/templates_4.1/includes/globalfooter.html
wdn/templates_4.1/includes/logo.html
wdn/templates_4.1/scripts/legacy.js

Because the CMS was recently updated to force https, most of the links in the includes were 301ing. This updates those links.
There is also a link to http://www.unl.edu/ in the header, which is not in an include. That will be much harder to fix.

update links to use https

---

wdn/templates_4.1/less/layouts/forms.less

type=radio,checkbox,submit were not showing a focus outline.

Always show a focus outline for inputs

---

wdn/templates_4.1/less/layouts/tables.less
wdn/templates_4.1/less/modules/tables.less

Improve color contrast for table header cells. At browsers widths under the ‘bp768’ breakpoint, the responsive table headers were white on a light background. At browser widths over the ‘bp768’ breakpoint, each responsive table would override the white with its own respective color and background-color. Now, the white table headers have been removed from the table body, and the contrast compliant color and background-color are applied at all browser widths, not just those above the ‘bp768’ breakpoint.
Borders are now present for table header cells in the table body for all tables, not just responsive tables.
The border-bottom has been removed from the abbreviation in the table header used to create responsive tables.
Coding style:
* New line for each selector.
* New lines in nested Less …

Table styling updates

---

wdn/templates_5.0/includes/global/search.html
wdn/templates_5.0/scss/components/_components.search.scss

- Update background overlay class for modal overlay
- Namespace Google search results class with ‘unl-‘
- Denote existing 4.1 directory results classes with brackets for later discussion
- Use media object for directory results
- Update utility classes used for layout
- Update Schema.org microdata
- Add '+1' to telephone links
- Remove commented out markup that is no longer needed
- Add margin-bottom to Google search results to prevent vertical collision with UNL directory results when viewed in narrow browser widths
- Add vertical space in between individual directory results with margin-bottom
- Update Google search results style overrides

Search results markup & styling

---

wdn/templates_4.1/less/layouts/footer.less

WebAudit expects framework icon classes (`.wdn-icon-*`) to contain the `aria-hidden=“true”` attribute for accessibility. However, `.wdn-icon-container` is not an icon itself; instead it can be applied to the parent element of an icon to prevent adjacent text from wrapping below it on a second line, treating icons like hanging indents.

Rename ‘.wdn-icon-container’ class

---

wdn/templates_4.1/scripts/js-css/unlalert.less

The z-index is too low for the alert and risks being covered by other elements.

Increase z-index for UNLalert

---

wdn/templates_4.1/includes/globalfooter.html

The `.wdn-icon-container` class name was updated to `.wdn-hang-icon` in #1113, but the markup was not also updated to reflect the name change. This fixes that.

Update global footer icon markup

---

sharedcode/affiliate/localFooter.html
sharedcode/localFooter.html
wdn/templates_4.1/includes/globalfooter.html

The way that AT implements this changed in aria 1.1 and now the way this is implemented in assistive technology is not consistent. We should update all of these to use `<h2>`, but adding an `aria-level="2"` has the same effect without having to change the styles.

ensure that a heading level of 2 is used for section headings in the footer

---

wdn/templates_5.0/scss/all.scss
wdn/templates_5.0/scss/deprecated/deprecated.bands.scss
wdn/templates_5.0/scss/deprecated/deprecated.columns.scss
wdn/templates_5.0/scss/deprecated/deprecated.forms.scss
wdn/templates_5.0/scss/deprecated/deprecated.grid.scss
wdn/templates_5.0/scss/deprecated/deprecated.helpers.scss
wdn/templates_5.0/scss/deprecated/deprecated.hero.scss
wdn/templates_5.0/scss/deprecated/deprecated.images.scss
wdn/templates_5.0/scss/deprecated/deprecated.pagination.scss
wdn/templates_5.0/scss/deprecated/deprecated.promo-image.scss
wdn/templates_5.0/scss/deprecated/deprecated.quote.scss
wdn/templates_5.0/scss/deprecated/deprecated.tables.scss
wdn/templates_5.0/scss/deprecated/deprecated.tabs.scss
wdn/templates_5.0/scss/deprecated/deprecated.text.scss

Deprecated styles still need to be added for plugins/widgets and to handle infographics and icons.

Add initial 4.1 deprecated styles to 5.0

---

.travis.yml
tests/Accessibility/phantomjs-axe.js
wdn/templates_4.1/scripts/search.js

Setting the url to search (`u` parameter) was not working at desktop widths. This appears to be due to the fact that the search form is never actually submitted on desktop. Instead, a frame is created via js, then cross frame communication is used to submit changes. Only the search query value is passed via the cross frame communication.
This fixes the issue by altering the initial search frame URL that used to include the parameters.
An example of such a configuration is:
```
<link rel="search" href="https://search.unl.edu/?u=https://admissions.unl.edu/" />
```

Fix search params on desktop

---

wdn/templates_5.0/includes/global/nav-toggle-group.html
wdn/templates_5.0/js-src/main.babel.js

#1164 
Bulk of the work occurred in the chat project: https://github.com/unl/VisitorChat/pull/361
This adds the chat initialization right back to where it was in 4.1.  It can possibly be moved later to a plugin of its own (?)

Closes #1164 - Re-add chat for 5.0

---

wdn/templates_5.0/examples/band_imagery.html
wdn/templates_5.0/js-src/band_imagery.js

- replaced outdated ids for band_imagery.html and increased scaling value in scale band-imagery example
- replaced deprecated el.load jquery method to el.on("load", cb)
Fixes #1243

Fix band-imagery using deprecated jQuery method

---

wdn/templates_5.0/js-src/search.babel.js

The test that compares siteHomepage to www.unl.edu looks for a trailing slash and that's what existed before in 4.1 when siteHomepage was generated by the nav JS

Add trailing slash when constructing siteHomepage

---

wdn/templates_5.0/scss/deprecated/deprecated.tabs.scss

This prevents tabs from being forced onto one row and instead lets them wrap as needed.

Set deprecated WDN Tabs to flex-wrap

---

wdn/templates_5.0/includes/global/nav-toggle-group.html

This particular nav tag is occasionally causing aXe Accessibility Metric errors in WebAudit related to duplicate ids.  Not exactly sure why it randomly fails, but believe it is some type of race condition.  This nav tag is only visible in mobile and skip-to assigns a random id to it when visible.  Adding an id to the nav tag will prevent skip-to from generating an id and will use assigned id.

Add id to dcf-nav-toogle-group nav tag to prevent skip-to from assigning random id to it

---

wdn/templates_5.0/js-src/plugins/ui/css/jquery-ui-wdn.scss

- Use framework colors for accordion border and background
- Set `.ui-widget` `font-family` to `inherit` instead of using Arial and Helvetica.

Fix jQuery UI accordion colors and fonts

---

wdn/templates_5.0/scss/deprecated/deprecated.forms.scss

Remove `vertical-align: middle` to vertically align deprecated buttons with current buttons.

Remove vertical-align: middle from deprecated buttons

---

wdn/templates_5.0/includes/global/footer-global-1.html
wdn/templates_5.0/includes/global/footer-global-2.html
wdn/templates_5.0/scss/components/_components.footer.scss
wdn/templates_5.0/scss/core.tmp.scss
wdn/templates_5.0/scss/critical.tmp.scss
wdn/templates_5.0/scss/deprecated.tmp.scss
wdn/templates_5.0/scss/pre.tmp.scss
wdn/templates_5.0/scss/print.tmp.scss

- Use `<small>` element for copyright.
- Change `.dcf-footer-stripe` to `.unl-footer-stripe`. The footer stripe is a theme style, not a DCF style.

Update footer markup

---

.gitignore
package-lock.json
wdn/templates_5.0/scss/components/_components.dev.scss
wdn/templates_5.0/scss/components/_components.headings.scss
wdn/templates_5.0/scss/core.tmp.scss
wdn/templates_5.0/scss/critical.tmp.scss
wdn/templates_5.0/scss/deprecated.tmp.scss
wdn/templates_5.0/scss/pre.tmp.scss
wdn/templates_5.0/scss/print.tmp.scss
wdn/templates_5.0/scss/variables/_variables.easing.scss
wdn/templates_5.0/scss/variables/_variables.timing.scss

- Add theme easing and timing variables to account for DCF update
- Ignore development-only styles
- Remove temp modal styles now found in DCF core
- Move heading ornament from ‘dev’ to ‘headings’ and use `currentColor`

 Update development-only styles

---

debug.shtml
package-lock.json

- Update DCF (includes [additions](https://github.com/d-c-n/dcf/pull/248) to the [lazy-load JavaScript](https://github.com/d-c-n/dcf/blob/master/assets/src/js/app/common/dcf-lazyLoad.js) to calculate image size and fill empty `data-sizes` attribute).
- Lazy load images on the debug page

Update DCF and lazy load images on debug page

---

wdn/templates_5.0/scss/elements/_elements.details-summary.scss

- Change cursor to pointer for summary to better indicate interactivity.
- Hide WebKit default arrow marker

Update summary cursor and arrow

---

wdn/templates_5.0/scss/deprecated/deprecated.bands.scss

Lighten `.wdn-light-complement-band` `background-color` for color contrast compliant links.

Update deprecated bands background colors

---

wdn/templates_5.0/includes/global/footer-global-1.html
wdn/templates_5.0/includes/global/footer-global-2.html
wdn/templates_5.0/includes/global/idm.html
wdn/templates_5.0/includes/global/nav-menu-1.html
wdn/templates_5.0/includes/global/nav-toggle-group.html
wdn/templates_5.0/includes/global/search.html
wdn/templates_5.0/includes/global/skip-nav.html
wdn/templates_5.0/includes/local/footer-local.html

- Update primary navigation `aria-label` - [Don’t use the word "nav" or "navigation" in the label]( https://css-tricks.com/how-to-section-your-html/#article-header-id-3)
- Capitalize first letter of search `aria-label` and add “form” for more clarity.
- Convert skipnav, IdM and footer `<nav>`s to `<div>`s - https://css-tricks.com/how-to-section-your-html/#article-header-id-1
- Update footer IDs
- Update footer logo `aria-label`
- Add `role` and `aria-label` to search form - https://css-tricks.com/how-to-section-your-html/#article-header-id-2
- Capitalize nav toggle group `aria-label`s
**This will require site owners to update their [local footer](https://github.com/unl/wdntemplates/blob/develop/wdn/templates_5.0/includes/local/footer-local.html) include files.**

Reduce usage of <nav>, update aria-labels

---

wdn/templates_5.0/includes/global/footer-global-2.html
wdn/templates_5.0/includes/local/footer-local.html

Add `aria-labelledby` attribute to footer lists.  Like PR #1327, this will require updates in UNLcms and communication to those not using UNLcms.

Add ARIA labels to footer lists

---

wdn/templates_5.0/scss/elements/_elements.details-summary.scss

I discovered that the styles and interactions for the custom marker are broken in Safari. 
- The marker is displayed below the summary instead of to the right of it.
- A user is forced to focus on another element before the marker is rotated from ‘+’ to ‘×’.
I’m reverting to browser defaults for consistency.

Revert some <details>, <summary> styles

---

wdn/templates_5.0/js-src/js-css/monthwidget.scss
wdn/templates_5.0/js-src/monthwidget.js

Remove monthwidget user interface that showed a date's events on hover. This content could not be accessed on touchscreen devices and, anecdotally, numerous users told me that they weren't even aware of the hover content. Removing this user interface also eliminates the Safari bug where the caption would move to the bottom of the calendar after hovering over a date.
Closes #1316

Remove monthwidet date hover UI (JS & CSS)

---

wdn/templates_5.0/scss/components/_components.heroes-legacy.scss
wdn/templates_5.0/scss/core.tmp.scss
wdn/templates_5.0/scss/critical.tmp.scss
wdn/templates_5.0/scss/deprecated.tmp.scss
wdn/templates_5.0/scss/pre.tmp.scss
wdn/templates_5.0/scss/print.tmp.scss

Add styles for legacy (4.1-style) heroes. 
Documentation will need to be added to show which utility classes are required to complete the legacy hero layout.

Add legacy hero CSS

---

wdn/templates_5.0/includes/global/head-2-local.html
wdn/templates_5.0/includes/global/head-2.html

To continue using 4.1 classes outside UNLcms, you'll need to manually include the stylesheet link in your `<head>` section. See: https://wdn.unl.edu/documentation/5.0/using-olddeprecated-classes-and-css

Remove deprecated.css link from head include files

---

package-lock.json
wdn/templates_5.0/includes/global/nav-menu-1.html
wdn/templates_5.0/includes/global/search.html
wdn/templates_5.0/js-src/navigation.babel.js
wdn/templates_5.0/js-src/search.babel.js
wdn/templates_5.0/scss/components/_components.dev.scss
wdn/templates_5.0/scss/components/_components.nav-menu.scss
wdn/templates_5.0/scss/components/_components.search.scss
wdn/templates_5.0/scss/critical.scss
wdn/templates_5.0/scss/critical.tmp.scss

Temporarily remove `prefers-reduced-motion` media query and revert to previously-used method for transitioning modal states for search and mobile navigation. This media query will be restored as soon as possible.

Temporarily remove reduced motion preference; update search & mobile nav modals

---

wdn/templates_5.0/js-src/jquery.js

The polyfill hack was causing issues with jquery colorbox.  
I was not able to replicate the issue that resulted in adding the hack, which was an unlikely edge case, so not adding an alternative fix at this time.  We can address if an issue occurs in the future.
This update addresses this issue: https://github.com/unl/wdntemplates/issues/1361

Remove jquery polyfill hack

---

wdn/templates_5.0/scss/components/_components.headings.scss
wdn/templates_5.0/scss/core.tmp.scss
wdn/templates_5.0/scss/elements/_elements.headings.scss
wdn/templates_5.0/scss/mixins/_mixins.typography.scss
wdn/templates_5.0/scss/utilities/_utilities.typography.scss

- Add mixin/utility to match the tighter `letter-spacing` and negative `margin-left` of headings
- Use mixin for heading `letter-spacing` and `margin-left`
- Move heading styles to new elements partial

Add mixin/utility to match heading letter-spacing

---

package-lock.json
wdn/templates_5.0/scss/components/_components.heroes-legacy.scss

- Hide the breadcrumbs wrapper instead of only the breadcrumbs.
- Apply reduced opacity to images and videos, not the whole hero group. If a photo credit is included, it too will have decreased opacity and fail color contrast compliance.

Fix legacy hero breadcrumbs display and image/video opacity

---

wdn/templates_5.1/scss/variables/_variables.colors.scss

Revert the "warning" color variable to orange until the notices are redesigned. The yellow isn't compatible with the current (old 4.x) design of the notices.

Revert warning color value

---

wdn/templates_5.1/js-src/events-band.js
wdn/templates_5.1/js-src/events.js

To better support virtual locations (zoom meeting), I updated the event's website to link locations with the web page URL defined to the URL.  This change makes the same change for our WDN events plugins. It also syncs the behavior between the events and events-band plugin for location display behavior.

Support location webpage url link

---

wdn/templates_5.2/scss/components/_components.app.scss
wdn/templates_5.2/scss/components/_components.nav-local.scss
wdn/templates_5.2/scss/components/_components.nav-menu.scss

- Hide/show calls to action in correct places for “mobile” and “desktop”
- Adjust button and link font-size, margin for app menu

Fix calls to action (Visit/Apply/Give) display for app templates

---

wdn/templates_5.2/js-src/navigation.babel.js

App templates do not have `dcf-menu-toogle` so need to add check to prevent javascript error.

Add check for desktopBtn for app templates

---

Gruntfile.js

This PR seeks to change the paths used by node-sass includePaths in Gruntfile.js from absolute paths to relative paths. In the event the absolute path contains certain characters (including colons), Grunt will complain it is unable to find the files to be included by the includePaths value.
For example, if the absolute path contains a colon:
`/var/www/html/dxg-dev.unl.edu:8440/vendor/unl/wdntemplates/node_modules/modularscale-sass/stylesheets`
```
Running "sass:main" (sass) task
Fatal error: Error: File to import not found or unreadable: modularscale.
on line 7 of wdn/templates_5.1/scss/variables/_variables.modular-scale.scss
from line 6 of wdn/templates_5.1/scss/variables/_variables.abbreviations.scss
from line 12 of wdn/templates_5.1/scss/critical.tmp.scss
>> @import 'modularscale';
``` …

Use relative paths for node-sass includePaths in Gruntfile.js

---

wdn/templates_5.2/includes/global/head-2-local.html
wdn/templates_5.2/includes/global/head-2.html
wdn/templates_5.2/includes/global/skip-nav.html

Tracking has been verified from my dev environment with these updates by alissaf@nrccua.org.
We need to determine if only applying to 5.2 and if not which versions need to support this tracking.  I don't know the intent of the tracking but I think only 5.2 is probably good.
Also I don't know what the urgency for this is and if approved whether it needs to go out before next WDN release.

Implement UNL sitewide pixel via Google Tag Manager

---

wdn/templates_5.2/js-src/plugins/mediaelement/mediaelement-and-player.js

This update will default the `aria-valuemax` which uses the `media.duration` to 0 if evaluates to NAN so to fix issue in web audit.
You can test in debug.shtml with:
```
<div class="dcf-mb-6">
<audio class="wdn_player" preload="auto" src="https://s3-us-west-2.amazonaws.com/agalmanac/090720/Hendrickson1.mp3"></audio>
<script>
window.addEventListener('inlineJSReady', function(){
WDN.initializePlugin('mediaelement_wdn');
});
</script>
</div>
```
and verify that the `aria-valuemax` of the div with class of `mejs-time-rail` has value of `0`. Note this value will change if the audio is played.

Default mediaelement duration to 0 if not a number

---

package-lock.json
wdn/templates_5.2/scss/variables/_variables.tables.scss

Responsive table fix was [merged](https://github.com/digitalcampusframework/dcf/pull/362#issuecomment-738961356) into the DCF `master` branch but not the DCF `2.0` branch.

Fix responsive table mobile display

---

wdn/templates_5.2/js-src/qa.js

Update to correctly add star to qa test link with recent change to `main.babel.js` which adds query string to the link.

Bug fix to display QA test star

---

wdn/templates_5.2/js-src/carousel.js

This fix is to possibly help with aria contrast issues with web audit so the first slide is not faded in on page load.
Can test from `{dev-wdntemplates-site}/wdn/templates_5.2/examples/#carousel.html`

Prevent fade on first carousel slide

---

Gruntfile.js
package-lock.json
package.json

Polyfill was causing font display issues if text was contained within elements that used object-fit. Object-fit is now supported by over 97% of browsers – and we no longer support Internet Explorer.

Remove object-fit polyfill

---

wdn/templates_5.3/js-src/js-css/slideshows.scss

Caption contains default `figcaption` color and fails color contrast compliance against the dark slideshow caption background. Thanks @beckyaiken for spotting this!

Fix caption color in slideshows

---

wdn/templates_5.3/js-src/events-band.js
wdn/templates_5.3/js-src/events.js

NOTE: WIP, until Events PR is merged https://github.com/unl/UNL_Events/pull/148
Added two new plugin settings:
* featured - if true will pull featured events from set calendar
* pinned_limit:  how many pinned events that may be included in results (defaults to 1). It should be less than `limit` (defaults to 10).
Also includes some cleanup:
* Allow calendar url path without trailing slash.
* Allow direct calendar path to `upcoming` or `featured` with or without trailing slash.
Usage:
```
<script>
WDN.setPluginParam('events', 'href', 'https://events-dev.unl.edu');
WDN.setPluginParam('events', 'title', 'UNL');
WDN.initializePlugin('events', {featured: true, limit:4, pinned_limit:2});
WDN.initializePlugin('events-band',{featured: true, limit:4, pinned_limit:2, rooms: true});
</script>
```
or …

Support featured events in events and events-band widgets

---

wdn/templates_5.3/scss/mixins/_mixins.background-images.scss
wdn/templates_5.3/scss/utilities/_utilities.background-images.scss

- Apply `background-size` to all variations of dots `background-image` utility classes
- Add missing `!important` to `background-image` ~~utilites~~ mixins

Add utility for dots background images

---

wdn/templates_5.3/scss/components/_components.datepickers.scss

`postition: relative` now causes the `box-shadow` to effectively disappear in Chrome.

(Temporarily?) remove datepicker date relative positioning & z-index

---

package-lock.json
wdn/templates_5.3/scss/components/_components.notices.scss

Currently, the default heading color is changed to cream (`#fefdfa`) for only the `.dcf-notice-heading`. This pull request applies the color change to all headings inside the notice – including those nested inside `.dcf-notice-message`.

Fix heading color in notices

---

wdn/templates_5.3/includes/global/head-2-local.html
wdn/templates_5.3/includes/global/head-2.html

Prevent browsers from double downloading both SVG and ICO icons: https://css-tricks.com/favicons-how-to-make-sure-browsers-only-download-the-svg-version/

Add `sizes="any”` to favicon.ico

---

wdn/templates_5.3/js-src/modals.babel.js

This update will allow youTube video embeds in WDN DCF Modals to autoplay and stop on modal open and close.
For the video to autoplay, embed iframe must have `allows` attribute with `autoplay` as one of the values.

Update Modal video events to handle YouTube embeds

---

package-lock.json
package.json
wdn/templates_5.3/js-src/bg-videos.babel.js
wdn/templates_5.3/js-src/main-wdn-plugins.babel.js

Note: Temporary points to my DCF PR for new/pending DCF feature: https://github.com/digitalcampusframework/dcf/pull/433
This is a start. I made some assumptions which may be wrong.
* Is automatically available on any WDN page
* attempts to add play/pause buttons to any element with class of `dcf-bg-video`
* uses localstorage to get state of playing/paused and defaults to play.
* should play/pause any video tag with `autoplay` and `muted` attributes.
* DCF Themeable I used play/pause svg markup from DCF slide show for now in both DCF and WDN. Either or both can be updated if want different.
Tested with
```
<div class="dcf-mt-6">
<div class="dcf-bg-video dcf-ratio dcf-ratio-16x9">
<video class="dcf-ratio-child dcf-obj-fit-cover" autoplay muted>
<source …
```

Implement DCF background video toggle

---

wdn/templates_5.3/scss/elements/_elements.progress.scss

Set `width` and/or `max-width` manually as needed rather than customize default.

Remove progress width and max-width

---

wdn/templates_5.3/includes/global/footer-global-2.html

This link will be included on the Safety at Nebraska site (which immediately precedes it in the footer).

Remove Security and Fire Safety Report link from footer

---

wdn/templates_5.3/scss/critical.scss
wdn/templates_5.3/scss/critical.tmp.scss

Add `@media screen` media query (already present in main.css) to critical.css for colors and background colors in print.

Add screen media query for colors in critical CSS

---

wdn/templates_5.3/scss/variables/_variables.notices.scss

Lighten text color for _info_ and _success_ notices.
Closes #1620

Fix info and success notice color contrast

---

wdn/templates_5.3/scss/utilities/_utilities.background-colors.scss
wdn/templates_5.3/scss/utilities/_utilities.colors.scss

Color and background classes that are dark-mode-specific (`@dark`) will no longer apply to both dark mode _and_ light mode. Instead, they will apply only to dark mode – as their name implies. Chaining classes together (e.g., `unl-bg-cream unl-bg-cream@dark`) achieves the previous result.

Move dark-mode-only colors and background-colors into dark mode media queries 

---

wdn/templates_5.3/includes/global/cta-header-1.html
wdn/templates_5.3/includes/global/logo-lockup-1.html
wdn/templates_5.3/includes/global/visit-header-1.html
wdn/templates_5.3/scss/components/_components.header.scss
wdn/templates_5.3/scss/critical.scss
wdn/templates_5.3/scss/critical.tmp.scss

- Remove mobile and desktop versions of COVID-19 header link
- Restore `padding-top` to logo lockup that was removed for COVID-19 link since it occupied the (roughly) equivalent vertical space.
- Remove custom `padding-top` now handled by utility class in the logo lockup.

Remove COVID-19 header link(s)

---

wdn/templates_5.3/scss/components/_components.nav-menu.scss

The `fixed` position of mobile menu gradient overlays was preventing taps for some menu links.

Remove mobile menu gradient overlays

---

package-lock.json

Bumped version of DCF in package-lock from old version
[Old Version](https://github.com/digitalcampusframework/dcf/commit/1cf246eae7e6b1ac1fb14fe26c66c4da49ac4d6e)
[New Version](https://github.com/digitalcampusframework/dcf/commit/564ee727a9236ba06a7440e4568eb08c7beafa74)

Bumped dcf version to current 3.0

---

wdn/templates_5.3/scss/variables/_variables.backgrounds.scss
wdn/templates_5.3/scss/variables/_variables.cards.scss

- Lighten `.dcf-card` `background-color`
- Swap values for `.unl-bg-light-gray` and `.unl-bg-lightest-gray` (`.unl-bg-light-gray` now uses the hex color for `.unl-bg-lightest-gray` and vice versa). Class names will now be accurate – `lightest` will no longer be darker than `light`.

Adjust light background-colors for dark mode

---

package-lock.json
wdn/templates_5.3/includes/global/apply-header-1.html
wdn/templates_5.3/includes/global/apply-header-2.html
wdn/templates_5.3/includes/global/give-header-1.html
wdn/templates_5.3/includes/global/give-header-2.html
wdn/templates_5.3/includes/global/visit-header-1.html
wdn/templates_5.3/includes/global/visit-header-2.html

Li were conflicting with hover action on popup due to markers overlaying other item. When hovering over "Visit" button the "Apply" button's marker was on top even though it's not visible.

Moved popup class to its own div

---

wdn/templates_5.3/scss/mixins/_mixins.colors.scss
wdn/templates_5.3/scss/utilities/_utilities.colors.scss

When `.unl-scarlet` is applied to a link, the `:visited`, `:hover` and `:active` states inherit the link state colors. This means the link is ~~cream~~ lightest-gray by default, but scarlet on `:hover`. Now the ~~cream~~ lightest-gray color is consistent across all states.

Fix scarlet link state colors in dark mode

---

wdn/templates_5.3/scss/mixins/_mixins.background-images.scss
wdn/templates_5.3/scss/utilities/_utilities.background-images.scss

Diagonal gradient background image can be added atop any framework `background-color` with a combination of the `unl-bg-diagonal-gradients` and `unl-bg-soft-light` utility classes.

Add background diagonal gradients mixin/utility

---

.github/workflows/duf_bump.yaml

Added new Github Workflow for bumping the DCF version automatically. It will make a pull request with the package-lock's DCF package commit version being updated. Due to the method for testing the last PR was closed #1681.
This Github Workflow will do the following:
1. Get the timestamp of the latest commit of DCF branch 3.0
2. Check to see if a commit has been made within the last hour
- If not it will exit the workflow
3. Get new commit hash and modify package-lock DCF version
4. Create new pull request
- If no changes were made to the package-lock no pull request will be made 
Pull requests will use these customizations:
```YAML
title: "Bump DCF"
body: "Updated DCF commit hash"
branch: "dcf-dump-branch"
commit-message: "Bumped DCF"
labels: dependency
reviewers: tommyneu
auto-merge: …
```

Added new github workflow

---

wdn/templates_5.3/js-src/analytics.babel.js

Sometimes google will load its own gtag.js which causes IDM not to be initialized. This now checks a different script to check if it has been initialized already

Fix issues with initialize not running on certain domains

---

wdn/templates_5.3/scss/variables/_variables.modals.scss

Increase modal-wrapper `max-height` to use more available screen real estate.

Adjust modal-wrapper max-height

---

wdn/templates_5.3/js-src/events.babel.js

This goes along with [events#209](https://github.com/unl/UNL_Events/pull/209)
Changes:
- Events with time mode 'TBD' will be displayed as `TBD` (This includes the abbr tag)
- Events with time mode 'STARTTIMEONLY' will be displayed with `Starts at`
- Events with time mode 'ENDTIMEONLY' will be displayed with `Ends at`

Added time mode support

---

wdn/templates_5.3/scss/components/_components.modals.scss

These styles are unnecessary. They're already handled by [DCF](https://github.com/digitalcampusframework/dcf/blob/3.0/scss/components/_components.modals.scss).

Remove modal style overrides

---

package-lock.json
wdn/templates_5.3/scss/variables/_variables.backgrounds.scss

For use with elements (e.g., cards, tab panels, dialogs) to "foreground" them above other elements by setting the `background-color` to white in light mode and a dark gray lighter than any other background colors in dark mode.
- Add `$bg-color-foreground` variable
- Pairs with [DCF 526](https://github.com/digitalcampusframework/dcf/pull/526) which adds mixin/utility class.

Add `bg-color-foreground` variable/mixin/utility

---

wdn/templates_5.3/scss/critical.scss
wdn/templates_5.3/scss/critical.tmp.scss

The `.unl` class is unnecessary. By removing the class, the critical CSS will match the styles in DCF core for [paragraphs](https://github.com/digitalcampusframework/dcf/blob/3.0/scss/elements/_elements.paragraphs.scss#L6-L12) and [lists](https://github.com/digitalcampusframework/dcf/blob/3.0/scss/elements/_elements.lists.scss#L12-L19).

Remove `.unl` class before paragraph and list selectors in critical CSS

---

wdn/templates_5.3/scss/components/_components.nav-local.scss

Adjust local nav column widths to use `auto` instead of `1fr`. Thanks, @badrobotbrain!
Closes #1752

Adjust local nav grid columns to allow for better text wrapping

---

wdn/templates_5.3/js-src/unlalert.babel.js

Closes #1775 
Renamed variables and functions. Added comments.
I have been having some issues with the alert data URL not updating when the cache is enabled.
I have this in the code 
// Are these two variables below needed?
// $alertToggle = $('#unlalert_toggle'),
// $alertContent = $('#_content'),

Added code to remove alert banner if alert data doesn't exist 

---

.gitignore
Gruntfile.js

Dart sass uses the absolute paths for source maps. This leaves us with `file://...` for all css source maps file references. These end up breaking when deployed to production. This PR fixes those source map references and adds the DCF files to the `wdn/templates_5.3` to reference them

Fix absolute paths and copy dcf files to wdn/templates_5.3

---

wdn/templates_6.0/scss/mixins/_background-images.scss
wdn/templates_6.0/scss/utilities/_background-images.scss
wdn/templates_6.0/scss/variables/_backgrounds.scss

Add `linear-gradient`-based `background-image`s, each consisting of a solid background color, hard stop and short, transparent region (at either the top or bottom of the section) to let the existing section `background-color` to show through. These can be used to create the illusion of objects breaking the plane.

Add background “shift” variables, mixins and utlities

---

wdn/templates_6.0/scss/components/_global.scss
wdn/templates_6.0/scss/mixins/_clip-paths.scss
wdn/templates_6.0/scss/mixins/_index.scss
wdn/templates_6.0/scss/utilities/_clip-paths.scss
wdn/templates_6.0/scss/utilities/_index.scss

- Add `clip-path`-based UNL stripes (as mixins/utilities) for top, bottom and both (`block`) of an element
- Move `.unl-frame-quad` from "components/global" to "utilities/clip-paths"

Add `clip-path` mixins/utilities, move `.unl-frame-quad` from "global"

---

wdn/templates_6.0/scss/variables/_forms.scss

Form help text color was being set to `$color-dark-gray-dark-mode` or `$light-gray` by default in DCF. So I switched it to be set to `$color-light-text-dark-mode` or `$gray-s1` in the WDN theme

Fix form help text color

---

vite.config.js
vite.wdnFinalJsUrlPlugin.js
vite.wdnImportVersion.js
wdn/templates_6.0/js-src/components/unl-alert.js

Changes:
- Added new vite plugin for added cache busting version to each import `?v={dep version}`
- Added cache busting version to all js imports
- Added cache busting version to CSS imports (loadStyleSheet)
- Update final url vite plugin to also add cache busting version for plugin url constants
- Updated alert to not have invalid URL due to additional parameters

Cache busting
