unl/wdntemplates

- sharedcode/affiliate/css/affiliate.css
- sharedcode/affiliate/less/affiliate.less
> Update affiliate template to 4.0

- wdn/templates_4.0/less/layouts/forms.less
Change Tungsten (difficult to read at smaller sizes) to Gotham
> Update legend style

- wdn/templates_4.0/less/layouts/unlalert.less
> Improve contrast of alert text to meet WCAG 2.0 AA

- .travis.yml
- build/composer.json
- tests/HTMLValidation/validate_shtml.phpt
- vagrant/dev/puphpet/config.yaml
This should make the testing more stable.  The official validator just broke.
> Use our own validator

- wdn/templates_4.0/examples/forms.html
- wdn/templates_4.0/less/layouts/forms.less
> Add new namespaced class to restore standard lists within form lists

- wdn/templates_4.1/includes/search.html
A good article about this: http://adrianroselli.com/2015/08/where-to-put-your-search-role.html
#865
> Improve placement of the search role

- sharedcode/localFooter.html
- wdn/templates_4.1/includes/search.html
- wdn/templates_4.1/less/layouts/footer.less
- wdn/templates_4.1/less/layouts/search.less
- wdn/templates_4.1/less/states/search.less
> Search and Footer updates

- wdn/templates_4.1/less/layouts/grid-mixins.less
- wdn/templates_4.1/less/layouts/grid.less
Add support for eighths, ninths, and tenths
> Add additional grid columns

- wdn/templates_4.1/includes/globalfooter.html
- wdn/templates_4.1/less/_mixins/colors.less
- wdn/templates_4.1/less/layouts/breadcrumbs.less
- wdn/templates_4.1/less/layouts/navigation.less
- wdn/templates_4.1/less/layouts/search.less
- wdn/templates_4.1/less/layouts/share.less
- wdn/templates_4.1/less/states/navigation.less
With flexbox, breadcrumbs occupy only the space they need and are truncated for trails with long and/or numerous breadcrumbs
> Breadcrumb layout fixes with flexbox

- wdn/templates_4.1/less/layouts/breadcrumbs.less
- wdn/templates_4.1/less/layouts/header.less
Site affiliation <div> element will always be present in the template, but may not be filled. This adjusts the display of the site title to better vertically center it on the adjacent 'N'
> Logo lockup adjustments

- wdn/templates_4.1/includes/idm.html
- wdn/templates_4.1/includes/share.html
* fix validation error for the share widget
* prevent the IDM widget from closing when its padding is clicked
> Improve code relating to pop up widgets

- wdn/templates_4.1/scripts/navigation.js
This will cause an error to be throw when interactiing with the nav.
> Fix homeCrumbLink not set when it is created automatically

- wdn/templates_4.1/includes/globalfooter.html
- wdn/templates_4.1/less/base/base.less
- wdn/templates_4.1/less/base/text.less
- wdn/templates_4.1/less/layouts/bands.less
- wdn/templates_4.1/less/layouts/footer.less
- wdn/templates_4.1/less/layouts/noscript.less
- wdn/templates_4.1/less/layouts/old-grid.less
- wdn/templates_4.1/less/layouts/resources.less
- wdn/templates_4.1/less/layouts/tables.less
- wdn/templates_4.1/less/modules/promo-image.less
- wdn/templates_4.1/less/modules/quote.less
- wdn/templates_4.1/less/modules/tables.less
- wdn/templates_4.1/less/states/regions.less
- wdn/templates_4.1/scripts/js-css/notices.less
Add UNL switchboard phone number to global footer
> Add phone to global footer

- sharedcode/localFooter.html
- wdn/templates_4.1/includes/globalfooter.html
- wdn/templates_4.1/includes/idm.html
- wdn/templates_4.1/includes/navigation-addons.html
- wdn/templates_4.1/includes/search.html
- wdn/templates_4.1/includes/share.html
- wdn/templates_4.1/less/layouts/footer.less
- wdn/templates_4.1/less/layouts/idm.less
- wdn/templates_4.1/less/layouts/wrapper.less
- wdn/templates_4.1/scripts/idm.js
- wdn/templates_4.1/scripts/socialmediashare.js
- wdn/templates_4.1/scripts/wdn-ui.js
This improve a11y in several ways
* fix a bug where `aria-hidden="true"` was being applied to the search form on full navigation
* Make sure input-drivers are focusable and reachable with screen readers
* better describe some controls
* hide icon-fonts from screen readers (which might try to read them)
There are some more improvements which we can make, but this is a good start.
> more a11y improvements

- wdn/templates_4.1/less/base/text.less
Line-height should be unitless.
> Remove unit from heading line-height

- wdn/templates_4.1/examples/events.html
- wdn/templates_4.1/scripts/events-band.js
- wdn/templates_4.1/scripts/events.js
https://github.com/unl/wdntemplates/issues/957
Per request from College of Law. Many sites have more or less a single building hosting all their events, and would like to show the room number in their widgets.
> Room number in Events and Events Band widget

- wdn/templates_4.1/scripts/idm.js
This will bring in profile icons from the avatar services supported
through directory.
> Use the directory avatar service

- wdn/templates_4.1/includes/globalfooter.html
> Fix 301 redirect for instagram url in global footer

- wdn/templates_4.1/less/layouts/header.less
Adjust site affiliation min-height (for sites with no site affiliation content present) to better vertically align the site title with the Nebraska 'N'.
> Improve site title vertical alignment

- wdn/templates_4.1/less/base/helpers.less
This is very similar to how bootstrap does it and allows for multiple aspect ratios as well as types of embeds.
> Add a wdn-responsive-embed class

- wdn/templates_4.1/less/modules/hero.less
Add margin-top to initial line if it appears after (instead of before) the impact line
> Margin-top for initial line

- wdn/templates_4.1/includes/navigation-addons.html
- wdn/templates_4.1/includes/share.html
- wdn/templates_4.1/less/layouts/idm.less
- wdn/templates_4.1/less/layouts/navigation.less
- wdn/templates_4.1/less/layouts/search.less
- wdn/templates_4.1/less/layouts/share.less
- wdn/templates_4.1/less/states/idm.less
- wdn/templates_4.1/less/states/navigation.less
- wdn/templates_4.1/less/states/search.less
- wdn/templates_4.1/less/states/share.less
- wdn/templates_4.1/scripts/navigation.js
- wdn/templates_4.1/scripts/socialmediashare.js
- wdn/templates_4.1/scripts/wdn-ui.js
Work still needs to be done to clean up the wdn-ui.js file and and change the aria-pressed state to false when clicking/tapping outside of share option popup.
> Update styles to hide/show containers based on the container's aria-hidden attribute 

- wdn/templates_4.1/less/layouts/footer.less
* Limited used of CSS columns to multi-column layouts
* Removed redundant rules
> Improve CSS column code in footer 

- wdn/templates_4.1/less/states/regions.less
Update footer logo CSS to target [regions that may be conditionally hidden](http://wdn.unl.edu/unledu-41-style-book#exceptions)
Fixes #1028
> Update CSS for hiding footer logos

- package.json
- tests/Accessibility/AccessibilityTester.php
- tests/Accessibility/accessibility-axe.phpt
- tests/Accessibility/accessibility-pa11y.phpt
- tests/Accessibility/phantomjs-axe.js
- wdn/templates_4.1/examples/audioplayer.html
- wdn/templates_4.1/examples/jqueryui.html
- wdn/templates_4.1/examples/videoplayer.html
- wdn/templates_4.1/examples/zentables.html
WebAudit will be moving to aXe core. For at least a month during the transition, both metrics will be running, so we should also run both metrics here. Once WebAudit drops pa11y, we can drop pa11y here too.
> Add accessibility checking via axe-core

- debug.shtml
- document.shtml
- fixed.shtml
- secure.shtml
- Updated 'UNL' breadcrumb to 'Nebraska' in framework debug, document, fixed, and secure files.
- Removed redundant title attributes
> Update 'UNL' breadcrumb to 'Nebraska'

- wdn/templates_4.1/scripts/monthwidget.js
The passed config should take precidence.
> Fix monthwidget defaultConfig overrides passed config

- sharedcode/localFooter.html
- wdn/templates_4.1/less/states/regions.less
- Add IDs to local footer code examples, allowing elements to be conditionally hidden
- Remove unnecessary rules, variables and mixins
Fixes #1025
Fixes #1026
> Update conditionally hidden regions

- wdn/templates_4.1/less/states/navigation.less
- wdn/templates_4.1/scripts/navigation.js
* Less selector changes to support cleaner animation of expand
* Use getBoundingClentRect to get subpixel values
> Adjust CSS/JS for navigation subpixel rendering

- wdn/templates_4.1/less/layouts/footer.less
Resolves footer layout issues caused by previous font-size updates (#1040). 
Fixes #1047
> Footer font-size/layout updates

- .gitattributes
- Gruntfile.js
Smudge file to replace '$DEP_VERSION' with version number.
> Smudge speedy_body_scripts.html

- wdn/templates_4.1/less/layouts/tables.less
- wdn/templates_4.1/less/modules/tables.less
- Remove redundant rules
- Improve use of media queries
- Restore border-collapse
- Adjust <th> background-color
- Scope <th> color and background-color to responsive table <tbody> @bp768
- Improve consistency of table striping
> Table styling improvements

- wdn/templates_4.1/less/base/text.less
- wdn/templates_4.1/less/layouts/footer.less
- wdn/templates_4.1/less/layouts/forms.less
- wdn/templates_4.1/less/layouts/grid.less
- wdn/templates_4.1/less/layouts/resources.less
- wdn/templates_4.1/less/layouts/search.less
- wdn/templates_4.1/less/layouts/share.less
- wdn/templates_4.1/less/modules/infographics.less
- wdn/templates_4.1/less/states/idm.less
- wdn/templates_4.1/less/states/search.less
- wdn/templates_4.1/less/states/share.less
- layouts/footer.less
- [states/idm.less](https://github.com/unl/wdntemplates/pull/1012#r74086184)
- [states/search.less](https://github.com/unl/wdntemplates/pull/1012#r74085726)
- states/share.less
> Use double quotes for attribute selectors

- wdn/templates_4.1/scripts/js-css/unlalert.less
- wdn/templates_4.1/scripts/unlalert.js
- Improve accessibility by changing 'toggle visibility' link to button and adding ARIA attributes
- Update alert design (colors, typography, layout)
**Before:**
**After:**
> UNL Alert design, a11y updates 

- debug.shtml
- wdn/templates_4.1/less/modules/tables.less
-Added styling for the `tbody th a` element
> Table fixes

- bio.shtml
- debug.shtml
- package-lock.json
- wdn/templates_5.0/includes/global/footer-global.html
- wdn/templates_5.0/includes/global/idm.html
- wdn/templates_5.0/includes/global/institution.html
- wdn/templates_5.0/includes/global/nav-secondary.html
- wdn/templates_5.0/includes/global/search.html
- wdn/templates_5.0/includes/local/footer-local.html
- wdn/templates_5.0/scss/all.scss
- wdn/templates_5.0/scss/components/_components.breadcrumbs.scss
- wdn/templates_5.0/scss/components/_components.buttons.scss
- wdn/templates_5.0/scss/components/_components.events.scss
- wdn/templates_5.0/scss/components/_components.footer.scss
- wdn/templates_5.0/scss/components/_components.forms.scss
- wdn/templates_5.0/scss/components/_components.header.scss
- wdn/templates_5.0/scss/components/_components.input-groups.scss
- wdn/templates_5.0/scss/components/_components.pagination.scss
- wdn/templates_5.0/scss/components/_components.paragraphs.scss
- wdn/templates_5.0/scss/components/_components.search.scss
- wdn/templates_5.0/scss/mixins/_mixins.backgrounds.scss
- wdn/templates_5.0/scss/mixins/_mixins.typography.scss
- wdn/templates_5.0/scss/variables/_variables.colors.scss
After this gets merged, I'll switch to feature branches for continued 5.0 development.
> Markup and CSS work for 5.0

- wdn/templates_4.1/includes/globalfooter.html
- Update 'Nebraska Today' link to `https://`
- Add 'Security and Fire Safety Report' link
- Update 'Policies' heading to 'Policies & Reports' better reflect the scope of the linked  content
> Update footer links

- debug.shtml
- package-lock.json
- Update DCF core
- Use utility class for header column-gap
- Update grids used in cards, untitled grid example and article footer
- Remove unnecessary examples
> Grid updates in markup

- wdn/templates_5.0/includes/global/idm.html
- wdn/templates_5.0/js-src/idm.babel.js
Because the upcoming usability tests and brand consultation will impact the layout and aesthetics of the header, the styling here is intentionally kept to a minimum. Additional styling will be added at a later date. The attributes have been reordered according to [http://codeguide.co/#html-attribute-order](http://codeguide.co/#html-attribute-order).
> IdM widget styling

- wdn/templates_4.1/less/all.less
- wdn/templates_4.1/less/modules/qa.less
- wdn/templates_4.1/scripts/main-execute-mods.js
- wdn/templates_4.1/scripts/qa.js
Attaches a star after the 'QA Test' link in the footer if the site has a Web Audit score of 90% or higher. A gold star is shown if 100%, otherwise it is silver.
Gold:
Silver:
> Add a QA star in the footer

- Gruntfile.js
- package-lock.json
- package.json
- wdn/templates_5.0/scss/all.scss
- Added glob patterns to all.scss file
- Added sassGlob related task and functions
- Added comment to Gruntfile.js for sass related functions
> - Added grunt-sass-globber package

- Gruntfile.js
Added comments to clarify RequireJS config object and related variables.
> Add clarification comments to gruntfile

- Gruntfile.js
- better explain what syncJsIgnore does in comment
- add glob pattern to exclude  *.src.js in syncJsIgnore variable
> Improvements to Gruntfile.js

- wdn/templates_5.0/js-src/search.babel.js
* Added styles to iframe to fill containing div with no border
* Added logic to remove search results on search close
* Updated setting siteHomepage.
> Fix search results

- wdn/templates_5.0/includes/local/app-search.html
- wdn/templates_5.0/scss/deprecated/deprecated.forms.scss
- Add color utility to search button
- Update deprecated buttons to match 5.0 styles
> Update deprecated and search button styles

- wdn/templates_5.0/scss/components/_components.nav-local.scss
Temporarily used flexbox until we have more time to troubleshoot CSS Grid in IE.
> Use flexbox for local nav grid fallback in IE

- Templates/app.dwt
- Templates/app_debug.dwt
- Templates/app_local.dwt
- Templates/debug.dwt
- Templates/fixed.dwt
- Templates/jsp.app.dwt.jsp
- Templates/jsp.app_debug.dwt.jsp
- Templates/jsp.app_local.dwt.jsp
- Templates/jsp.debug.dwt.jsp
- Templates/jsp.fixed.dwt.jsp
- Templates/jsp.local.dwt.jsp
- Templates/jsp.unlaffiliate.dwt.jsp
- Templates/jsp.unlaffiliate_debug.dwt.jsp
- Templates/jsp.unlaffiliate_local.dwt.jsp
- Templates/local.dwt
- Templates/php.app.dwt.php
- Templates/php.app_debug.dwt.php
- Templates/php.app_local.dwt.php
- Templates/php.debug.dwt.php
- Templates/php.fixed.dwt.php
- Templates/php.local.dwt.php
- Templates/php.unlaffiliate.dwt.php
- Templates/php.unlaffiliate_debug.dwt.php
- Templates/php.unlaffiliate_local.dwt.php
- Templates/unlaffiliate.dwt
- Templates/unlaffiliate_debug.dwt
- Templates/unlaffiliate_local.dwt
1) Add editable regions for global nav 2) Add breadcrumb wrapper 3) Add optionalfooter region
> Template updates

- Templates/app.dwt
- Templates/app_debug.dwt
- Templates/app_local.dwt
- Templates/debug.dwt
- Templates/fixed.dwt
- Templates/jsp.app.dwt.jsp
- Templates/jsp.app_debug.dwt.jsp
- Templates/jsp.app_local.dwt.jsp
- Templates/jsp.debug.dwt.jsp
- Templates/jsp.fixed.dwt.jsp
- Templates/jsp.local.dwt.jsp
- Templates/jsp.unlaffiliate.dwt.jsp
- Templates/jsp.unlaffiliate_debug.dwt.jsp
- Templates/jsp.unlaffiliate_local.dwt.jsp
- Templates/local.dwt
- Templates/php.app.dwt.php
- Templates/php.app_debug.dwt.php
- Templates/php.app_local.dwt.php
- Templates/php.debug.dwt.php
- Templates/php.fixed.dwt.php
- Templates/php.local.dwt.php
- Templates/php.unlaffiliate.dwt.php
- Templates/php.unlaffiliate_debug.dwt.php
- Templates/php.unlaffiliate_local.dwt.php
- Templates/unlaffiliate.dwt
- Templates/unlaffiliate_debug.dwt
- Templates/unlaffiliate_local.dwt
- ux-test.shtml
* Rename Instance*Editable to Templat*Editable and fix wdnInclude for fixed php templates
* Update fixed jsp templates to have fixed path
* Revert .shtml files
* More .shtml reverts
> Fix template bugs (#1238)

- wdn/templates_5.0/scss/deprecated/deprecated.forms.scss
Missing generic input styles for number and tel inputs.
> Add number and tel input types to input styles

- wdn/templates_5.0/includes/global/head-2-local.html
- wdn/templates_5.0/includes/global/head-2.html
Fix suggested by PageSpeed: https://developers.google.com/speed/pagespeed/insights/?url=www.unl.edu
> Add preload for chat css so can be loaded before chat js executes

- wdn/templates_5.0/js-src/analytics.babel.js
Also remove old bindApps() function for 'apps' drawer that hasn't existed since 3.1
> Update IDs in analytics for page tracking

- debug.shtml
- package-lock.json
- wdn/templates_5.0/scss/core.tmp.scss
- wdn/templates_5.0/scss/elements/_elements.details-summary.scss
- Update DCF.
- Use `<details>` and `<summary>` elements for [native accordions](https://css-tricks.com/quick-reminder-that-details-summary-is-the-easiest-way-ever-to-make-an-accordion/).
> Add theme styles for <details>, <summary> elements

- wdn/templates_5.0/includes/global/search.html
Add `background-color` in case image fails to load.
> Add background-color utility to search form

- debug.shtml
- package-lock.json
- package.json
- wdn/templates_5.0/js-src/lazy-load.babel.js
- wdn/templates_5.0/js-src/main-wdn-plugins.babel.js
- Update DCF and Node modules
- Require and configure lazy-load for 5.0
- Lazy load images on the debug page
> Update image lazy-loading

- wdn/templates_5.0/js-src/unlalert.babel.js
> Prevent alerts from displaying when page is in a iframe

- wdn/templates_5.0/js-src/events-band.js
- wdn/templates_5.0/js-src/events.js
- wdn/templates_5.0/js-src/js-css/events-band.scss
- wdn/templates_5.0/js-src/js-css/events.scss
- wdn/templates_5.0/scss/objects/_objects.grid.scss
- Update `<headers>` to `<header>`
- Wrap `.unl-offset-grid` in a feature query [`@supports (display:grid)`]
- Fix events list and events band grid fallback for Internet Explorer
- Improve events band JS indentations (code style)
> Fix events list and band typos and IE grid fallback

- wdn/templates_5.0/includes/global/nav-menu-1.html
- wdn/templates_5.0/js-src/navigation.babel.js
- wdn/templates_5.0/scss/components/_components.nav-menu.scss
Desktop nav menu would not close after pressing the menu ("hamburger") icon. Adjust classes and JavaScript to fix.
> Adjust nav menu state classes

- wdn/templates_5.0/includes/global/head-2.html
- wdn/templates_5.0/scss/critical.scss
- wdn/templates_5.0/scss/critical.tmp.scss
- Update the link to critical CSS file from relative to absolute path
- Update nav menu state class used in critical CSS
> Fix critical CSS

- wdn/templates_5.0/js-src/events-band.js
- wdn/templates_5.0/js-src/events.js
- wdn/templates_5.0/js-src/js-css/events.scss
- Adjust `margin-bottom` for event teasers
- Use utility classes for ordering elements (in JS files)
- Convert tabs to spaces
- Adjust comments
- Remove extra empty line at end of events.scss file
> Fix events display

- wdn/templates_5.0/js-src/wdn.babel.js
Note: if approved will need to make the same change on 5.1 branch
> Add Third Party cookie support via samesite

- package-lock.json
- wdn/templates_5.0/js-src/wdn.babel.js
- wdn/templates_5.1/scss/critical.tmp.scss
- wdn/templates_5.1/scss/deprecated.tmp.scss
- wdn/templates_5.1/scss/main.tmp.scss
- wdn/templates_5.1/scss/pre.tmp.scss
- wdn/templates_5.1/scss/print.tmp.scss
Applying WDN.setCookie update made in 5.0 to 5.1.
> Add samesite cookie support to WND.setCookie

- debug.shtml
- wdn/templates_5.0/js-src/idm.babel.js
Note: If approved I'll make the same changes to 5.1
> Update IDM to retrieve logged in user data

- package-lock.json
- package.json
- wdn/templates_5.1/scss/main.tmp.scss
- Update DCF and Node modules
- Update `main.tmp.scss` to includes new `_elements.html` partial from core (enables smooth scrolling)
> Update DCF, Node modules, Sass partial for smooth scrolling

- wdn/templates_5.1/scss/components/_components.buttons.scss
Fix colors for `:visited` inverse buttons
> Add styles scoped for :visited inverse buttons

- wdn/templates_5.1/js-src/search.babel.js
Fix default search link wave error: https://wave.webaim.org/report#/https://www.unl.edu
> Do not clear content from default search link

- wdn/templates_5.1/js-src/jquery.js
- wdn/templates_5.1/js-src/plugins/jquery-migrate.js
Do we want to also upgrade for 5.0?
> Upgrade jquery to v3.5.1

- wdn/templates_5.2/scss/deprecated/deprecated.tables.scss
Exclude deprecated table styles from jQuery UI datepicker.
> Fix deprecated tables for jQuery UI datepicker

- wdn/templates_5.2/includes/global/footer-global-1.html
- wdn/templates_5.2/includes/global/footer-global-2.html
- wdn/templates_5.2/scss/components/_components.footer.scss
- Update footer institution title, copyright styling
- Update footer link state styles
> Update footer styles

- wdn/templates_5.2/includes/global/apply-header-2.html
- wdn/templates_5.2/includes/global/apply-nav-2.html
- wdn/templates_5.2/includes/global/visit-header-2.html
- wdn/templates_5.2/includes/global/visit-nav-2.html
- wdn/templates_5.2/scss/components/_components.cta.scss
- Update CTA link URLs
- Update CTA `:visited` link styles
> Update CTA links

- wdn/templates_5.2/includes/global/head-1.html
- wdn/templates_5.2/scss/generic/_generic.color-scheme.scss
Temporarily disable dark mode to allow time for more testing.
> Temporarily disable dark mode

- wdn/templates_5.2/scss/mixins/_mixins.background-colors.scss
> Fix variable used in background-color mixin (5.2 dark mode preview)

- wdn/templates_5.2/scss/mixins/_mixins.background-colors.scss
> Fix variable used in background-color mixin (5.2)

- debug.shtml
- package-lock.json
- wdn/templates_5.2/scss/variables/_variables.abbreviations.scss
- Update DCF (which includes [updates for responsive tables](https://github.com/digitalcampusframework/dcf/pull/362) and [Sass logic for abbreviations styles](https://github.com/digitalcampusframework/dcf/pull/361))
- Increase abbreviation `font-size` and remove `bottom-border`
- Remove `font-size` utilities from example abbreviations in debug file
> Update abbreviation styles (and DCF responsive tables)

- package-lock.json
- Update DCF with styling fix for `<input type="range">`
- Update Node modules
> Update DCF, Node modules

- wdn/templates_5.2/js-src/js-css/unlalert.scss
- wdn/templates_5.2/js-src/unlalert.babel.js
The cream-on-orange color scheme for the alert was not color contrast compliant.
> Update UNL Alert styles

- wdn/templates_5.2/js-src/plugins/body-scroll-lock.js
Note: This update won't fix iOS modal issue but need to update to latest version.  I will attempt to fix iOS issue in DCF and fix will likely depend on this version update.
> Update body-scroll-lock to latest version

- package-lock.json
- package.json
fix for https://github.com/unl/wdntemplates/issues/1467
> DCF Modal and Tabs fix via DCF update and other NPM updates.

- package-lock.json
- wdn/templates_5.2/js-src/cta-nav.babel.js
- wdn/templates_5.2/js-src/idm.babel.js
- wdn/templates_5.2/scss/components/_components.idm.scss
- Update DCF, Node modules
- Remove mouseover/leave for CTA (Visit/Apply/Give) popovers
- Update IdM styles to match CTA popovers
> Make CTA and IdM styles consistent

- wdn/templates_5.2/scss/elements/_elements.images.scss
> Remove space below footer caused by tracking pixel

- wdn/templates_5.2/scss/elements/_elements.code.scss
- wdn/templates_5.2/scss/main.tmp.scss
- wdn/templates_5.2/scss/mixins/_mixins.fonts.scss
> Update monospace font for code

- package-lock.json
- wdn/templates_5.3/scss/variables/_variables.sizing.scss
- Add variables to accommodate new additional lengths for height, width, margin and padding
- Update DCF
> Add additional lengths (height, width, margin, padding)

- wdn/templates_5.3/scss/variables/_variables.borders.scss
Change from .75em to 1em for a more circular shape.
> Fix pill border-radius

- wdn/templates_5.3/includes/global/footer-global-2.html
- wdn/templates_5.3/scss/components/_components.footer.scss
- Update footer colors & background-color
- Remove color utility class (handled by footer CSS)
> Update footer colors & background-color

- wdn/templates_5.3/js-src/events-band.js
Usage: `WDN.initializePlugin('events-band',{use_band_background: false});`
> Add use_band_background config option to events band plugin

- package-lock.json
- wdn/templates_5.3/scss/deprecated/deprecated.tables.scss
- wdn/templates_5.3/scss/generic/_generic.color-scheme.scss
- wdn/templates_5.3/scss/variables/_variables.color-palette.scss
- wdn/templates_5.3/scss/variables/_variables.datepickers.scss
- wdn/templates_5.3/scss/variables/_variables.forms.scss
- Add datepicker dialog `background-color` variables
- Update DCF & Node modules
- Add `font-weight` variable for form `<legend>`
- Adjust deprecated tables for datepicker
- Add form required label color variables
- Remove unsupported `$hue` from `scale-color` function in `$scarlet-shade` color variable
These changes are needed to support https://github.com/unl/UNL_Events/pull/146
> Add variables and adjust deprecated tables for forms & datepickers

- wdn/templates_5.3/scss/components/_components.header.scss
- wdn/templates_5.3/scss/components/_components.idm.scss
Fix Visit/Apply/Give links color in popover menus (light mode)
> Fix CTA link color

- debug.shtml
- package-lock.json
- package.json
- wdn/templates_5.3/js-src/pagination.babel.js
- wdn/templates_5.3/scss/main.tmp.scss
Note: This currently points to my DCF pagination PR for DCF
> Implement DCF Pagination

- package-lock.json
- wdn/templates_5.3/js-src/slideshows.babel.js
- Update Node modules
- Add `focusable=“false”` to slideshow SVG icons
> Add focusable=“false” to slideshow SVG icons

- Gruntfile.js
- package-lock.json
- package.json
- wdn/templates_5.3/js-src/autoplay-videos.babel.js
- wdn/templates_5.3/js-src/js-css/slideshows.scss
- wdn/templates_5.3/js-src/main-wdn-plugins.babel.js
- wdn/templates_5.3/scss/critical.tmp.scss
- wdn/templates_5.3/scss/deprecated.tmp.scss
- wdn/templates_5.3/scss/legacy.tmp.scss
- wdn/templates_5.3/scss/main.tmp.scss
- wdn/templates_5.3/scss/pre.tmp.scss
- wdn/templates_5.3/scss/print.tmp.scss
Videos may not necessarily be in the background, and they may not necessarily loop. We want our pause/play toggle for videos that autoplay on page load.
- Rename Background Video Toggle to _Autoplay_ Video Toggle
- Do not load autoplay video JS by default since autoplay videos aren't on every page of the website
**Do not merge until DCF is updated to include https://github.com/digitalcampusframework/dcf/pull/441 once it's approved.**
> Update JS for renamed BG video toggle

- wdn/templates_5.3/includes/global/head-2-local.html
- wdn/templates_5.3/includes/global/js-body.html
- wdn/templates_5.3/includes/global/skip-nav.html
- Remove GTM `<script>` from `head-2-local.html`
- Move GTM `<noscript>` from `skipnav.html` to `js-body.html`
> Update GTM script/noscript locations 

- wdn/templates_5.3/includes/global/footer-global-2.html
Update ‘Emergency Planning and Preparedness’ (https://emergency.unl.edu/) link to ‘Safety at Nebraska’ (https://safety.unl.edu/)
> Update emergency/safety link in footer

- package-lock.json
- wdn/templates_5.3/scss/components/_components.forms-checkboxes-radios.scss
~Need to update DCF first before merging.~ DCF has been updated.
Can be tested with the following code:
```
<form class="dcf-form" action="?" method="post">
<fieldset class="dcf-m-0 dcf-p-0 dcf-b-0">
<legend class="dcf-legend">Campus</legend>
<div class="dcf-form-group dcf-d-inline-flex dcf-flex-nowrap dcf-p-1 dcf-rounded dcf-b-1 dcf-b-solid unl-b-light-gray">
<div class="dcf-input-switch">
<input id="campus-city" name="campus" type="radio" value="city" checked="">
<label for="campus-city">City</label>
</div>
<div class="dcf-input-switch">
<input id="campus-east" name="campus" type="radio" value="east">
<label for="campus-east">East</label>
</div>
<div class="dcf-input-switch">
<input id="campus-innovation" name="campus" type="radio" value="innovation">
<label …
```
> Add radio toggle switch buttons component

- package-lock.json
- package.json
- wdn/templates_5.3/scss/critical.tmp.scss
- wdn/templates_5.3/scss/deprecated.tmp.scss
- wdn/templates_5.3/scss/legacy.tmp.scss
- wdn/templates_5.3/scss/main.tmp.scss
- wdn/templates_5.3/scss/pre.tmp.scss
- wdn/templates_5.3/scss/print.tmp.scss
- wdn/templates_5.3/scss/variables/_variables.hr.scss
- Update DCF and Node modules
- Add styles for `<hr>` element (horizontal rule)
> Add styles for <hr> element (horizontal rule)

- package-lock.json
- wdn/templates_5.3/scss/components/_components.forms-checkboxes-radios.scss
- wdn/templates_5.3/scss/components/_components.forms.scss
- wdn/templates_5.3/scss/variables/_variables.forms.scss
Fix label margin conflicts and incorrect `border-radius` on the buttons.
> Fix styles for radio toggle switch buttons component

- package-lock.json
Includes fix for `<select>` `border-radius` in input groups
> Update DCF (fix <select> corners in input groups)

- package-lock.json
- package.json
This fixes broken scroll animations.
> Update GSAP to 3.11.1

- Templates/affiliate.dwt
- Templates/affiliate_debug.dwt
- Templates/affiliate_local.dwt
- Templates/app.dwt
- Templates/app_debug.dwt
- Templates/app_local.dwt
- Templates/debug.dwt
- Templates/fixed.dwt
- Templates/jsp.affiliate.dwt.jsp
- Templates/jsp.affiliate_debug.dwt.jsp
- Templates/jsp.affiliate_local.dwt.jsp
- Templates/jsp.app.dwt.jsp
- Templates/jsp.app_debug.dwt.jsp
- Templates/jsp.app_local.dwt.jsp
- Templates/jsp.debug.dwt.jsp
- Templates/jsp.fixed.dwt.jsp
- Templates/jsp.local.dwt.jsp
- Templates/local.dwt
- Templates/php.affiliate.dwt.php
- Templates/php.affiliate_debug.dwt.php
- Templates/php.affiliate_local.dwt.php
- Templates/php.app.dwt.php
- Templates/php.app_debug.dwt.php
- Templates/php.app_local.dwt.php
- Templates/php.app_local.dwt.twig
- Templates/php.debug.dwt.php
- Templates/php.fixed.dwt.php
- Templates/php.local.dwt.php
- Templates/php.local.dwt.twig
Change `<!-- Instance` to `<!-- Template`
> Fix editable region comments

- wdn/templates_5.3/js-src/search.babel.js
Due to issues with the google custom search engine we are removing the auto submitting search results
> Commented out the search auto submit

- wdn/templates_5.3/scss/critical.tmp.scss
- wdn/templates_5.3/scss/deprecated.tmp.scss
- wdn/templates_5.3/scss/legacy.tmp.scss
- wdn/templates_5.3/scss/main.tmp.scss
- wdn/templates_5.3/scss/mixins/_mixins.background-blend-modes.scss
- wdn/templates_5.3/scss/pre.tmp.scss
- wdn/templates_5.3/scss/print.tmp.scss
- wdn/templates_5.3/scss/utilities/_utilities.background-blend-modes.scss
Add `background-blend-mode: soft-light`. For use with #1650.
> Add background-blend-modes mixin/utility

- package-lock.json
- wdn/templates_5.3/scss/critical.tmp.scss
- wdn/templates_5.3/scss/deprecated.tmp.scss
- wdn/templates_5.3/scss/legacy.tmp.scss
- wdn/templates_5.3/scss/main.tmp.scss
- wdn/templates_5.3/scss/pre.tmp.scss
- wdn/templates_5.3/scss/print.tmp.scss
- wdn/templates_5.3/scss/variables/_variables.progress.scss
DCF [480](https://github.com/digitalcampusframework/dcf/pull/480) needs to be approved and merged before merging this PR.
> Add progress spinner component

- Gruntfile.js
- debug.shtml
- package-lock.json
- wdn/templates_5.3/js-src/collapsible-fieldsets.babel.js
- wdn/templates_5.3/js-src/js-css/collapsible-fieldsets.scss
- wdn/templates_5.3/scss/critical.tmp.scss
- wdn/templates_5.3/scss/deprecated.tmp.scss
- wdn/templates_5.3/scss/legacy.tmp.scss
- wdn/templates_5.3/scss/main.tmp.scss
- wdn/templates_5.3/scss/pre.tmp.scss
- wdn/templates_5.3/scss/print.tmp.scss
- wdn/templates_5.3/scss/variables/_variables.collapsible-fieldset.scss
Added collapsible fieldsets that use the functionality of the toggle buttons to give them there interactivity
This goes along with the PR in [dcf#479](https://github.com/digitalcampusframework/dcf/pull/479)
> Collapsible Fieldsets

- wdn/templates_5.3/includes/global/apply-header-1.html
- wdn/templates_5.3/includes/global/give-header-1.html
- wdn/templates_5.3/includes/global/visit-header-1.html
- wdn/templates_5.3/js-src/cta-nav.babel.js
- wdn/templates_5.3/scss/variables/_variables.popups.scss
- Update markup to use DCF popups for Visit/Apply/Give CTAs
- Update Sass variables for popups
- Remove JavaScript now handled by DCF popup
> Use DCF popups for Visit/Apply/Give CTAs

- package-lock.json
- wdn/templates_5.3/js-src/js-css/collapsible-fieldsets.scss
This goes along with [DCF#491](https://github.com/digitalcampusframework/dcf/pull/491) and implements logic to prevent transitions
> Animation block

- debug.shtml
- wdn/templates_5.3/js-src/main-wdn-plugins.babel.js
> Cta nav fix

- wdn/templates_5.3/js-src/events.babel.js
- wdn/templates_5.3/js-src/js-css/events.scss
- Add icons to ICS and RSS buttons
- Remove stripes from event list heading
- Display events list as grid if space allows
> Update events component layout

- package-lock.json
> Bumped dcf version

- wdn/templates_5.3/js-src/tabs.babel.js
Re-added wdn_tabs due to larger than previously thought volume of pages that are using them
> re-added the wdn_tabs

- wdn/templates_5.3/scss/mixins/_mixins.background-colors.scss
- wdn/templates_5.3/scss/mixins/_mixins.colors.scss
- wdn/templates_5.3/scss/utilities/_utilities.background-colors.scss
- wdn/templates_5.3/scss/utilities/_utilities.colors.scss
- wdn/templates_5.3/scss/variables/_variables.color-palette.scss
Orange was missing from the framework
> Added brand-kappa and orange

- wdn/templates_5.3/js-src/search.babel.js
Search will be updating but almost everything should be the same. The route to the embed version will be different, and the postMessage data for new searching will be different
> Updated for new version of search

- README.md
> Update README for 5.3

- wdn/templates_5.3/scss/components/_components.buttons.scss
Pairs with https://github.com/digitalcampusframework/dcf/pull/506
> Add dark-mode-only button styles

- wdn/templates_5.3/includes/global/favicon/manifest.webmanifest
This size no longer exists in the repo.
> Remove 192px favicon from webmanifest

- wdn/templates_5.3/js-src/events.babel.js
- Reduce event heading `line-height`
- Increase event month `letter-spacing`
> Adjust events component line-height and letter-spacing

- debug.shtml
- wdn/templates_5.3/includes/global/apply-header-1.html
- wdn/templates_5.3/includes/global/give-header-1.html
- wdn/templates_5.3/includes/global/visit-header-1.html
Popups classes where not consistent with other dcf components
This goes along with https://github.com/digitalcampusframework/dcf/pull/510
> Replaced all popup buttons classes with their new versions

- document.shtml
- fixed.shtml
- secure.shtml
- wdn/templates_5.3/includes/global/apply-header-1.html
- wdn/templates_5.3/includes/global/apply-header-2.html
- wdn/templates_5.3/includes/global/apply-nav-2.html
- wdn/templates_5.3/includes/global/footer-global-2.html
- wdn/templates_5.3/includes/global/visit-header-1.html
- wdn/templates_5.3/includes/global/visit-header-2.html
- wdn/templates_5.3/includes/global/visit-nav-2.html
Went through and replaced any links that were 301 on web audit
> Fix 301 links from web audit

- debug.shtml
- wdn/templates_5.3/includes/global/apply-header-1.html
- wdn/templates_5.3/includes/global/give-header-1.html
- wdn/templates_5.3/includes/global/visit-header-1.html
- wdn/templates_5.3/js-src/collapsible-fieldsets.babel.js
This PR goes along with [DCF#513](https://github.com/digitalcampusframework/dcf/pull/513)
The changes that have been made are:
- Fix bug with popups flashing open on page load
- Fix bug with collapsible field sets flashing horizontal scroll bar on close
- Updated debug.shtml
> Misc toggle fixes

- wdn/templates_5.3/js-src/idm.babel.js
This goes along with [Directory#217](https://github.com/unl/UNL_Directory/pull/217)
> Replaced references for planet red with directory

- wdn/templates_5.3/includes/global/favicon/manifest.webmanifest
The URL path was missing `global/`
> Fix URL path to favicon in manifest.webmanifest

- wdn/templates_5.3/includes/global/footer-global-2.html
- Replace "Established 1869" with copyright year range
- Update current year from 2023 to 2024
> Update copyright year to 2024 in footer

- wdn/templates_5.3/js-src/events.babel.js
Remove `.add` from `.setAttribute`
> Fix `.setAttribute('role', 'list')` for Events component

- wdn/templates_5.3/js-src/events.babel.js
> Fix .setAttribute('role', 'list') for Events component (part 2)

- wdn/templates_5.3/includes/global/footer-global-2.html
> Update copyright year to 2024 in footer (Redo)

- debug.shtml
- wdn/templates_5.3/js-src/events.babel.js
- wdn/templates_5.3/js-src/js-css/events.scss
This will go along with an update to the featured events on events.unl.edu
> Added end time/all day to events widget and updated styles

- .github/workflows/dcf_bump.yaml
Github action is now targeting the incorrect location in the file
> Changed file target to match package lock file

- wdn/templates_5.3/scss/mixins/_mixins.colors.scss
- wdn/templates_5.3/scss/utilities/_utilities.colors.scss
Add `@mixin scarlet-at-dark` and `.unl-scarlet@dark` utility class.
> Add scarlet-at-dark mixin/utility class

- wdn/templates_5.3/scss/mixins/_mixins.background-blend-modes.scss
- wdn/templates_5.3/scss/utilities/_utilities.background-blend-modes.scss
Add mixin/utility for `background-blend-mode: multiply`
> Add mixin/utility for `background-blend-mode: multiply`

- wdn/templates_5.3/scss/mixins/_mixins.background-images.scss
- wdn/templates_5.3/scss/utilities/_utilities.background-images.scss
- Add single diagonal gradient mixin/utility
- Add `$imp` to `bg-diagonal-gradients` (multiple) mixin
> Add single diagonal gradient mixin/utility

- package-lock.json
- wdn/templates_5.3/scss/components/_components.buttons.scss
Pairs with [this](https://github.com/digitalcampusframework/dcf/pull/520) DCF pull request.
> Add state-based styles for button-as-link (`.dcf-btn-as-link`)

- wdn/templates_5.3/includes/global/search.html
- wdn/templates_5.3/includes/local/affiliate-search.html
The search label is missing it's rounded corners
> Added dcf-rounded-left to search label

- Gruntfile.js
- wdn/templates_5.3/js-src/search-selects.babel.js
- wdn/templates_5.3/scss/components/_components.search-selects.scss
- wdn/templates_5.3/scss/critical.tmp.scss
- wdn/templates_5.3/scss/deprecated.tmp.scss
- wdn/templates_5.3/scss/legacy.tmp.scss
- wdn/templates_5.3/scss/main.tmp.scss
- wdn/templates_5.3/scss/pre.tmp.scss
- wdn/templates_5.3/scss/print.tmp.scss
- wdn/templates_5.3/scss/variables/_variables.search-and-selects.scss
Pairs with https://github.com/digitalcampusframework/dcf/pull/529
> Add search-and-select/combobox component

- package-lock.json
- package.json
There was a bug on mobile devices where if you scroll down the page a little the page would scroll you back up to the top. Updating gsap seems to have fixed the issue
> Scroll To Top Bug

- wdn/templates_5.3/js-src/search.babel.js
This goes along with changes in search.unl.edu
> Added analytics events for search modal open and close

- wdn/templates_5.3/includes/global/head-2.html
- wdn/templates_5.3/js-src/analytics.babel.js
Changes: 
- Updated webanalytics.unl.edu to larue.unl.edu to avoid ad blockers
- Added ID to larue.unl.edu script tag
- Added logic to load larue.unl.edu in `analytics.babel.js` if not already in the head
> Web analytics update

- Templates/affiliate_cloud.dwt
- Templates/affiliate_debug.dwt
- Templates/affiliate_local.dwt
- Templates/app_cloud.dwt
- Templates/app_debug.dwt
- Templates/app_local.dwt
- Templates/cloud.dwt
- Templates/debug.dwt
- Templates/jsp.affiliate_cloud.dwt.jsp
- Templates/jsp.affiliate_debug.dwt.jsp
- Templates/jsp.affiliate_local.dwt.jsp
- Templates/jsp.app_cloud.dwt.jsp
- Templates/jsp.app_debug.dwt.jsp
- Templates/jsp.app_local.dwt.jsp
- Templates/jsp.cloud.dwt.jsp
- Templates/jsp.debug.dwt.jsp
- Templates/jsp.local.dwt.jsp
- Templates/local.dwt
- Templates/php.affiliate_cloud.dwt.php
- Templates/php.affiliate_debug.dwt.php
- Templates/php.affiliate_local.dwt.php
- Templates/php.app_cloud.dwt.php
- Templates/php.app_debug.dwt.php
- Templates/php.app_local.dwt.php
- Templates/php.app_local.dwt.twig
- Templates/php.cloud.dwt.php
- Templates/php.debug.dwt.php
- Templates/php.local.dwt.php
- Templates/php.local.dwt.twig
- wdn/templates_6.0/includes/local/footer-local.html
> Add `data-template` attribute to Templates files

- wdn/templates_6.0/includes/global/footer-global-3-big.html
- wdn/templates_6.0/scss/components/_footer.scss
Hide Herbie by default, and only show when `animation-timeline` is supported.
> Update footer Herbie Husker markup and fallback styles

- .env
- wdn/templates_6.0/js-src/components/unl-search.js
Changes:
- Added dev environment variable for search URL
> Dev Search URL

- .github/workflows/dcf_bump.yaml
Periodically the github action fails which sends me an email. Failure usually occurs when LATEST_TIMESTAMP fails to get most recent commit date due to an unknown reason. This will retry 3 time and will hopefully fail gracefully if it does
> Fix github action

- Templates/app_debug.dwt
- Templates/app_local.dwt
- Templates/debug.dwt
- Templates/jsp.app_debug.dwt.jsp
- Templates/jsp.app_local.dwt.jsp
- Templates/jsp.debug.dwt.jsp
- Templates/jsp.local.dwt.jsp
- Templates/local.dwt
- Templates/php.app_debug.dwt.php
- Templates/php.app_local.dwt.php
- Templates/php.app_local.dwt.twig
- Templates/php.debug.dwt.php
- Templates/php.local.dwt.php
- Templates/php.local.dwt.twig
- wdn/templates_6.0/includes/global/header-global-1-local.html
Changes:
- Added `header-global-1-local.html` and updated `header-global-1.html` to the CDN link
- Updated the local templates
> Added header-global-1-local

- debug-clean.shtml
Debug clean was still using the old 5.3 template with invalid virtual includes
> Fix debug-clean
